server:
  port: 8080
  tomcat:
    max-threads: 50

spring:
  profiles:
    active: ${env:dev}
  application:
    name: springboot-demo-server
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?createDatabaseIfNotExist=true&autoReconnect=true&characterEncoding=utf-8
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect:
          org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379